/**
 * Extracts the design-system palette from the web app's globals.css and emits it
 * as a typed TS module for React Native.
 *
 * Direction matters: globals.css is the source of truth, not a copy of this
 * output. Two hand-maintained palettes drift within a week — the moment someone
 * tunes --ink-3 for contrast on web and forgets the native file, the two
 * products stop being the same product. Generating one from the other makes
 * that impossible by construction.
 *
 * Only literal colours cross the boundary. `color-mix()` and `var()` chains stay
 * on the web side and are re-derived in TS, because React Native's StyleSheet
 * has no cascade to resolve them against.
 *
 * Run: npm run build -w @hermes/tokens
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const CSS = join(here, "../../../apps/web/app/globals.css");
const OUT = join(here, "../src/palette.generated.ts");

let css;
try {
  css = readFileSync(CSS, "utf8");
} catch {
  throw new Error(
    `Cannot read ${CSS}. The web app's globals.css is the source of truth for ` +
      `every colour token; update this path if the app moves.`,
  );
}

/** Pull the declaration body of a selector's first block. */
function block(startMarker) {
  const i = css.indexOf(startMarker);
  if (i === -1) throw new Error(`selector not found in globals.css: ${startMarker}`);
  let depth = 0;
  for (let j = i; j < css.length; j++) {
    if (css[j] === "{") depth++;
    else if (css[j] === "}") {
      depth--;
      if (depth === 0) return css.slice(i + startMarker.length, j);
    }
  }
  throw new Error(`unbalanced braces after ${startMarker}`);
}

/** Literal colour values only — anything computed stays on the web side. */
function colors(body) {
  const out = {};
  const re = /--([a-z0-9-]+):\s*([^;]+);/gi;
  let m;
  while ((m = re.exec(body))) {
    const [, name, raw] = m;
    const value = raw.trim();
    if (value.startsWith("color-mix") || value.startsWith("var(") || value.includes("gradient")) continue;
    if (!/^(#|rgba?\()/.test(value)) continue;
    out[name] = value;
  }
  return out;
}

const light = colors(block(":root {"));
const dark = { ...light, ...colors(block(':root[data-theme="dark"] {')) };

const missing = Object.keys(light).filter((k) => !(k in dark));
if (missing.length) throw new Error(`dark theme is missing: ${missing.join(", ")}`);

const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const emit = (obj) =>
  Object.entries(obj)
    .map(([k, v]) => `  ${camel(k)}: ${JSON.stringify(v)},`)
    .join("\n");

writeFileSync(
  OUT,
  `/* GENERATED by packages/tokens/scripts/extract.mjs — do not edit.
   Source of truth: app/globals.css. Re-run \`npm run build -w @hermes/tokens\`
   after changing a colour token there. */

export const lightPalette = {
${emit(light)}
} as const;

export const darkPalette: Record<keyof typeof lightPalette, string> = {
${emit(dark)}
};

export type PaletteKey = keyof typeof lightPalette;
`,
);

console.log(`✓ ${Object.keys(light).length} colour tokens → src/palette.generated.ts`);
