/**
 * Standalone app targets — one codebase, twelve genuinely different apps.
 *
 * Play Store rejects "Spam and Minimum Functionality" and Apple rejects guideline
 * 4.3 duplicate apps. The defence is not a different icon: it is a different
 * name, a different store description, a different first screen, a different
 * permission set and a different job to do. This file is the single source of
 * truth for those identities, and scripts/check-targets.mjs refuses a build
 * where two targets are too similar to survive review.
 *
 * Each target names the product modules it exposes from lib/products.ts.
 */
export const TARGETS = [
  {
    id: "passport-photo",
    name: "Passport Photo Maker",
    bundleId: "co.dropby.passportphoto",
    tagline: "Passport & visa photos in 30 seconds",
    storeCategory: "Photography",
    aso: ["passport photo", "visa photo", "id photo", "photo print size"],
    color: "#1d4ed8",
    permissions: ["CAMERA", "PHOTOS"],
    products: ["passport-photo"],
    firstScreen: "camera",
  },
  {
    id: "pdf-tools",
    name: "PDF Toolkit: Merge & Sign",
    bundleId: "co.dropby.pdftools",
    tagline: "Merge, split, compress, sign PDFs",
    storeCategory: "Productivity",
    aso: ["pdf merge", "pdf compress", "sign pdf", "pdf converter"],
    color: "#b91c1c",
    permissions: ["FILES"],
    products: ["pdf-tools"],
    firstScreen: "tool-grid",
  },
  {
    id: "room-redesign",
    name: "Room Redesign: AI Interior",
    bundleId: "co.dropby.roomredesign",
    tagline: "See your room in five new styles",
    storeCategory: "Lifestyle",
    aso: ["interior design", "room design", "home decor ideas"],
    color: "#7c3aed",
    permissions: ["CAMERA", "PHOTOS"],
    products: ["room-redesign"],
    firstScreen: "camera",
  },
  {
    id: "subtitles-voice",
    name: "Subtitles & Voice-over",
    bundleId: "co.dropby.subtitlesvoice",
    tagline: "Captions for video, voice from text",
    storeCategory: "Video Players & Editors",
    aso: ["subtitles", "captions", "text to speech", "srt"],
    color: "#0f766e",
    permissions: ["FILES", "MICROPHONE"],
    products: ["subtitles", "voiceover"],
    firstScreen: "chooser",
  },
  {
    id: "resume-builder",
    name: "Resume Builder & ATS Check",
    bundleId: "co.dropby.resumebuilder",
    tagline: "Build a resume that passes screening",
    storeCategory: "Business",
    aso: ["resume maker", "cv maker", "ats resume", "bio data"],
    color: "#0369a1",
    permissions: ["FILES"],
    products: ["resume-builder", "resume-checker", "application-writer"],
    firstScreen: "form",
  },
  {
    id: "shop-toolkit",
    name: "Shop Toolkit: Bills & Catalogue",
    bundleId: "co.dropby.shoptoolkit",
    tagline: "Invoices, catalogue and orders for your shop",
    storeCategory: "Business",
    aso: ["invoice maker", "gst bill", "catalogue maker", "udyam"],
    color: "#166534",
    permissions: ["CAMERA", "FILES", "CONTACTS"],
    products: ["invoice-maker", "catalogue", "order-loop", "digital-card", "booking-page", "bill-tracker", "fee-tracker"],
    firstScreen: "dashboard",
  },
  {
    id: "toolbox",
    name: "Everyday Tools & Photo Fix",
    bundleId: "co.dropby.toolbox",
    tagline: "Photos, documents and small jobs in one app",
    storeCategory: "Tools",
    aso: ["background remover", "photo editor", "id photo", "tools"],
    color: "#475569",
    permissions: ["CAMERA", "PHOTOS"],
    products: ["bg-remove", "signature-maker", "card-maker", "photo-repair", "product-photo", "worksheet-maker", "translate-doc", "study-helper", "cover-maker", "marksheet-maker", "notes-from-audio"],
    firstScreen: "grid",
  },
  {
    id: "sarkarhealth",
    name: "SarkarHealth: Doctors in Indore",
    bundleId: "co.dropby.sarkarhealth",
    tagline: "Find and call doctors and clinics in Indore",
    storeCategory: "Medical",
    aso: ["doctors in indore", "clinic", "hospital", "chemist"],
    color: "#0e7490",
    permissions: ["LOCATION"],
    products: [],
    directory: "sarkarhealth",
    firstScreen: "directory",
  },
  {
    id: "sarkarmarketplace",
    name: "Indore Business Directory",
    bundleId: "co.dropby.indoredirectory",
    tagline: "Every local business in Indore, with phone numbers",
    storeCategory: "Business",
    aso: ["indore business", "local directory", "shops near me"],
    color: "#a16207",
    permissions: ["LOCATION"],
    products: [],
    directory: "sarkarmarketplace",
    firstScreen: "directory",
  },
  {
    id: "sarkarcars",
    name: "Car Service & Dealers Indore",
    bundleId: "co.dropby.carsindore",
    tagline: "Car dealers, garages, denting and cleaning",
    storeCategory: "Auto & Vehicles",
    aso: ["car service indore", "car dealer", "denting painting"],
    color: "#9a3412",
    permissions: ["LOCATION"],
    products: [],
    directory: "sarkarcars",
    firstScreen: "directory",
  },
  {
    id: "tap-sprint",
    name: "Tap Sprint: Reflex Game",
    bundleId: "co.dropby.tapsprint",
    tagline: "Thirty seconds, how fast are you?",
    storeCategory: "Games",
    aso: ["reflex game", "tap game", "reaction test", "offline games"],
    color: "#db2777",
    permissions: [],
    products: [],
    game: "tap-sprint",
    firstScreen: "game",
    ads: { rewarded: "extra lives", interstitial: "between rounds" },
  },
  {
    id: "word-duel",
    name: "Word Duel: Word Puzzle",
    bundleId: "co.dropby.wordduel",
    tagline: "Sixty seconds of word making",
    storeCategory: "Games",
    aso: ["word game", "word puzzle", "offline word games"],
    color: "#4f46e5",
    permissions: [],
    products: [],
    game: "word-duel",
    firstScreen: "game",
    ads: { rewarded: "hint pack", interstitial: "between rounds" },
  },
];

export const byId = (id) => TARGETS.find((t) => t.id === id);
export const productTargets = () => TARGETS.filter((t) => t.products.length);
export const directoryTargets = () => TARGETS.filter((t) => t.directory);
export const gameTargets = () => TARGETS.filter((t) => t.game);
