/**
 * The wellness family's audio runtime: one audio session, one way to fire a cue, one bed.
 *
 * ── Why this file exists ───────────────────────────────────────────────────────────────
 *
 * Six screens now play sounds and three of them own a timer. Without this file each screen would
 * carry its own `setAudioModeAsync`, its own rewind-before-play dance, its own "is the preference
 * off" check and its own bed lifecycle — and the first one to get the rewind wrong would fire a cue
 * that does not restart, on the one screen nobody tested. The merge game's `playSound()` is the
 * proof this shape works; this is that shape, shared and extended.
 *
 * ── The rule that decides every choice here ────────────────────────────────────────────
 *
 * **Audio is feedback, never a rule.** No cue is load-bearing: a phone on silent, a device that
 * refuses the audio session, an asset that failed to bundle — every path through this module
 * degrades to "the screen still works, silently". Nothing here is awaited by a control, nothing
 * can reject into a render, and `fire()` cannot throw.
 *
 * ── Why the bank is an object and not a hook ───────────────────────────────────────────
 *
 * The tempting API is one hook that loads whichever players a screen asks for. It cannot be built
 * honestly: a hook must be called a fixed number of times per render, a screen's cue list is data,
 * and `cues.map(useAudioPlayer)` trips the rules-of-hooks lint — which is not being pedantic, it is
 * the exact class of bug that makes React lose track of state. Two earlier drafts of this file
 * tried to hide the loop behind a helper and both were flagged, correctly.
 *
 * So the split is explicit and enforced by the type system:
 *
 *   1. The **screen** loads its players with `useAudioPlayer`, one literal call per asset. Verbose,
 *      obvious, and the only form React actually guarantees.
 *   2. `WellnessAudio` is a **plain class** — no hooks at all — that turns those players into the
 *      behaviour: the switch, the rewind, the fallback, the bed. It is constructed from a screen's
 *      `useMemo` and is safe to hold in a ref or a stable variable.
 *
 * The first draft's other mistake is worth recording too: the bank subscribed to the settings store
 * itself, which meant its `cue` callback's identity changed on every tick of a running session (the
 * store re-emits) and any effect depending on it re-ran ten times a second. The preferences are now
 * passed *in*, once per render, and mirrored into fields that the fire path reads — so `cue` and
 * `say` are stable for the life of the screen and a timer callback captured three seconds ago still
 * sees the switch as it is now.
 *
 * ── What it deliberately does not do ───────────────────────────────────────────────────
 *
 * - **It does not take over the audio session.** `mixWithOthers` means a person listening to music
 *   while they breathe keeps their music and gets the cues over it. `playsInSilentMode: false`
 *   obeys the ringer switch, which is the control people actually use to silence an app.
 * - **It does not play in the background.** The bed pauses when the app is suspended. That is a
 *   real limitation, written down in `docs/wellness-sound.md` rather than hidden: keeping audio
 *   alive with the screen off needs a background audio mode and a longer conversation with both
 *   stores.
 * - **There is no voice.** The first version spoke its phase changes with a formant synthesizer in
 *   this repo, and it was removed for sounding robotic and unclear on a real phone. The reasoning,
 *   and what replaced each thing the voice was carrying, is recorded in `scripts/make-wellness-sounds.mjs`
 *   and in `docs/wellness-sound.md`. Nothing here speaks, so there is no voice switch to explain.
 */
import type { AudioPlayer } from "expo-audio";
import { setAudioModeAsync } from "expo-audio";
import { useSettings } from "./settings";

/**
 * Every cue the wellness screens can play, as an asset id.
 *
 * One flat map rather than a `require()` at each call site: Metro resolves a required asset at
 * build time, so the list of files that ship has to be static and visible in one place. It is also
 * why a screen passes a *name* ("in") rather than a path — a name that is not in this map is a
 * TypeScript error instead of a silent nothing.
 *
 * Generated by `scripts/make-wellness-sounds.mjs`; the recipe is that file plus the two helpers in
 * `scripts/lib/`, so these are ours outright and can be re-rendered, not merely re-used.
 */
export const WELLNESS_CUES = {
  /** Breathe, Stretch, Sleep — the in-breath. Rising. */
  in: require("../assets/wellness/cue-in.wav"),
  /** The out-breath. Falling — the exact mirror of `in`. */
  out: require("../assets/wellness/cue-out.wav"),
  /** A phase that holds. Flat and quiet, the one cue with no direction in it. */
  hold: require("../assets/wellness/cue-hold.wav"),
  /** A session finished. Three notes up a major triad, slowly. */
  done: require("../assets/wellness/cue-done.wav"),
  /** A routine's movement changed: short, low, no melody. */
  tick: require("../assets/wellness/cue-tick.wav"),
  /** Walk — the pace changed. Two notes, so it is not mistaken for a phase turn. */
  interval: require("../assets/wellness/cue-interval.wav"),
  /** Water — a glass logged. A drop landing. */
  drop: require("../assets/wellness/cue-drop.wav"),
  /** Japa — one bead. Deliberately the shortest sound in the set: it plays up to 108 times. */
  bead: require("../assets/wellness/cue-bead.wav"),
  /** Sleep — a round finished. A swell with no transient, because somebody is falling asleep. */
  swell: require("../assets/wellness/cue-swell.wav"),
  /**
   * Walk — a fast interval, a return to easy, and the last fast one. Added when the spoken cues
   * were removed: "faster", "ease off" and "this is the last one" are the three things a walker with
   * one earbud in needs, and a tone can carry all three as a shape.
   */
  fast: require("../assets/wellness/cue-fast.wav"),
  easy: require("../assets/wellness/cue-easy.wav"),
  last: require("../assets/wellness/cue-last.wav"),
  /** Stretch — the closing wind-down movement. Lower and slower than `tick`. */
  relax: require("../assets/wellness/cue-relax.wav"),
  /**
   * Japa — the 108th bead: the bead struck twice over a low fifth. This replaced both a spoken
   * "round done" and an earlier single-strike `beadRound` cue, which nothing else then used.
   */
  round: require("../assets/wellness/cue-round.wav"),
} as const;

export type CueName = keyof typeof WELLNESS_CUES;

/** The bed. One file, two screens, looped. */
export const WELLNESS_BED = require("../assets/wellness/drone.wav");

/** How loud a cue sits. Headroom, not taste — see `DRONE_VOLUME`. */
const CUE_VOLUME = 0.85;
/**
 * The bed is mixed well under the cues on purpose. It is a continuous sound and the cues are
 * transients, so equal file peaks would make the bed the loudest thing in the session — and a bed
 * you cannot hear a cue over is worse than no bed.
 */
const DRONE_VOLUME = 0.3;

/**
 * The audio session, configured once per process.
 *
 * A module-level promise rather than a per-screen effect: six screens each calling
 * `setAudioModeAsync` on mount would be six round trips to the platform for one setting, and the
 * last to resolve would win. Failure is swallowed because there is nothing a screen could usefully
 * do about it — that branch is "the app is silent and fully working".
 */
let audioMode: Promise<void> | null = null;

function ensureAudioMode(): Promise<void> {
  if (!audioMode) {
    audioMode = setAudioModeAsync({
      // Obey the ringer switch: this is how people silence an app.
      playsInSilentMode: false,
      // Never stop somebody's music to play a chime.
      interruptionMode: "mixWithOthers",
    }).catch(() => {});
  }
  return audioMode;
}

/**
 * Fire a cue. Fire-and-forget by design.
 *
 * The rewind is the part that matters and the part that is easy to omit: `play()` on a player that
 * has already reached the end resumes at the end and produces nothing, so a cue that fires on every
 * phase turn would sound exactly once per session. `seekTo(0)` is deliberately not awaited —
 * awaiting it would delay the sound by a tick, and a cue that arrives late is worse than one that
 * arrives on time.
 */
function fire(player: AudioPlayer, volume: number) {
  // Guarded because this is called from timer callbacks on devices that may have no audio route at
  // all, and an exception here would take down a running session.
  try {
    player.volume = volume;
    void player.seekTo(0).catch(() => {});
    player.play();
  } catch {
    /* No audio on this device. The session continues. */
  }
}

/** The players a screen has loaded, keyed by the name it will fire them by. */
export type CuePlayers = {
  cues?: Partial<Record<CueName, AudioPlayer>>;
  bed?: AudioPlayer | null;
};

/** What a screen must tell the bank about the person's preferences, once per render. */
export type SoundPrefs = {
  cuesOn: boolean;
  droneOn: boolean;
};

/** A player that plays a cue: the bound form, for a screen that wants to hand one to a child. */
export type CueFn = (name: CueName) => void;
/**
 * The audio behaviour for one screen, built from the players the screen loaded.
 *
 * A class rather than a closure-returning function so the screen can hold it in a `useMemo` or a
 * ref and be certain its identity does not matter: every method reads the current preferences out
 * of a field, so a stale reference still behaves correctly.
 */
export class WellnessAudio {
  private readonly players: CuePlayers;
  /** Mirrored from the render that built this bank; read at fire time, never captured by a hook. */
  private prefs: SoundPrefs;
  /** The bed's intent, so `startBed` is idempotent without the screen tracking it. */
  private bedRunning = false;

  /** Fired with the cue's name the moment it actually plays. For a test or a debug readout. */
  onCue?: (name: CueName) => void;

  constructor(players: CuePlayers, prefs: SoundPrefs) {
    this.players = players;
    this.prefs = prefs;
  }

  /**
   * Adopt the current render's preferences.
   *
   * Called by the screen on every render (a one-line effect is the natural place). This is what
   * lets `cue` and `say` stay stable while still respecting a switch that was flipped a moment ago:
   * the method object never changes, only the field it reads.
   */
  syncPrefs(prefs: SoundPrefs) {
    this.prefs = prefs;
  }

  get cuesAreOn(): boolean {
    return this.prefs.cuesOn;
  }

  get bedIsOn(): boolean {
    return this.prefs.droneOn;
  }

  /** Fire the cue with this name. A no-op when the person has turned cues off. */
  cue: CueFn = (name) => {
    if (!this.prefs.cuesOn) return;
    const player = this.players.cues?.[name];
    if (!player) return;
    void ensureAudioMode();
    fire(player, CUE_VOLUME);
    this.onCue?.(name);
  };

  /**
   * Start the bed, if the person wants it. Idempotent — a screen may call it on every phase without
   * restarting the loop, which is what makes it safe to call from an effect.
   */
  startBed = () => {
    const bed = this.players.bed;
    if (!this.prefs.droneOn || this.bedRunning || !bed) return;
    this.bedRunning = true;
    void ensureAudioMode();
    try {
      bed.loop = true;
      bed.volume = DRONE_VOLUME;
      bed.play();
    } catch {
      this.bedRunning = false;
    }
  };

  /** Stop the bed. Safe to call when it never started, and safe to call twice. */
  stopBed = () => {
    const bed = this.players.bed;
    if (!this.bedRunning || !bed) return;
    this.bedRunning = false;
    try {
      bed.pause();
      void bed.seekTo(0).catch(() => {});
    } catch {
      /* silent */
    }
  };
}

/**
 * Build the bank for one screen.
 *
 * A plain function — no hooks — so it can be called from a `useMemo`:
 *
 *     const audio = useMemo(
 *       () => makeWellnessAudio({ cues: { in: cueIn, out: cueOut }, bed }),
 *       [cueIn, cueOut, bed],
 *     );
 *     useEffect(() => audio.syncPrefs({ cuesOn, droneOn }), [audio, cuesOn, droneOn]);
 *     useEffect(() => () => audio.stopBed(), [audio]);
 *
 * Three lines of wiring per screen, all of it visible, and `audio.cue` is stable so a timer can
 * hold it.
 */
export function makeWellnessAudio(players: CuePlayers, prefs: SoundPrefs): WellnessAudio {
  return new WellnessAudio(players, prefs);
}

/**
 * The three preferences, read from the settings store, as the shape `makeWellnessAudio` wants.
 *
 * A tiny hook rather than three lines in each screen because the field names and the store keys are
 * the kind of thing that drifts: one screen reading `settings.soundOn` (which does not exist) would
 * silently be `undefined` and its cues would be permanently off.
 */
export function useSoundPrefs(): SoundPrefs {
  const { settings } = useSettings();
  return {
    cuesOn: settings.cuesOn,
    droneOn: settings.droneOn,
  };
}

/** The settings shape `setMuted` writes, and the hook that writes it. */
export type SettingsWriter = (patch: { cuesOn?: boolean; droneOn?: boolean }) => void;

/**
 * One switch that actually silences the app, for the speaker icon on a running screen.
 *
 * This exists because the first version of those icons was wrong, and the way it was wrong is worth
 * recording. Each header toggle flipped `cuesOn` alone, while the screens that spoke went on speaking
 * — so tapping a speaker icon left the app *still talking*. (That voice has since been removed
 * entirely; the lesson about the control outlived it.) A mute control that does not mute is worse
 * than no control, because the person believes it worked and stops looking for the real one.
 *
 * So the icon is a **master** mute: it turns both remaining layers off together, and back on
 * together. `muted` here means "all of them are off", which makes the icon's filled/empty state
 * honest rather than a guess.
 *
 * The asymmetry is deliberate: muting takes effect immediately in the running session, while
 * un-muting only stores the preference — nothing should start talking at you because you tapped a
 * speaker, so the sound comes back on the next phase turn or the next session.
 */
export function setMuted(write: SettingsWriter, muted: boolean): void {
  write({ cuesOn: !muted, droneOn: !muted });
}

/** True when every layer is off, so a speaker icon knows which icon to draw. */
export function isMuted(prefs: SoundPrefs): boolean {
  return !prefs.cuesOn && !prefs.droneOn;
}
