var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__174pcn6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0z3b0qr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1v09kk2.js")
R.c("server/chunks/ssr/[root-of-the-server]__1w1fafx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_01q5ebj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0h1fh0l._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_wvthf._.js")
R.c("server/chunks/ssr/_1whe3l6._.js")
R.c("server/chunks/ssr/app_brand-router_[brand]_brand-landing_tsx_089b_9j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1h4k0e-._.js")
R.c("server/chunks/ssr/_1j6l_yv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_0hhsz1j.js")
R.m(80345)
module.exports=R.m(80345).exports
