import { DateInput } from '@/components';
import { useAuth } from '@/contexts/auth-context';
import { supabase } from '@/lib/supabase';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import {
    ActivityIndicator,
    Alert,
    ScrollView,
    StyleSheet,
    Text,
    TextInput,
    TouchableOpacity,
    View,
} from 'react-native';
import QRCode from 'react-native-qrcode-svg';

type VisitorType = 'expected' | 'walk-in' | 'delivery' | 'service' | 'guest';

export default function PreApproveVisitor() {
    const router = useRouter();
    const { profile, currentRole } = useAuth();

    const [visitorName, setVisitorName] = useState('');
    const [visitorPhone, setVisitorPhone] = useState('');
    const [vehicleNumber, setVehicleNumber] = useState('');
    const [visitorType, setVisitorType] = useState<VisitorType>('guest');
    const [expectedDate, setExpectedDate] = useState<Date>(new Date());
    const [expectedTime, setExpectedTime] = useState<Date | null>(null);
    const [purpose, setPurpose] = useState('');

    const [isLoading, setIsLoading] = useState(false);
    const [generatedOTP, setGeneratedOTP] = useState<string | null>(null);
    const [visitorData, setVisitorData] = useState<any>(null);

    const handleSubmit = async () => {
        // Validation
        if (!visitorName.trim()) {
            Alert.alert('Error', 'Please enter visitor name');
            return;
        }

        // Indian mobile number validation (10 digits starting with 6-9)
        const phoneRegex = /^[6-9]\d{9}$/;
        if (!visitorPhone.trim() || !phoneRegex.test(visitorPhone.trim())) {
            Alert.alert('Error', 'Please enter a valid 10-digit Indian mobile number');
            return;
        }

        if (!profile || !currentRole) {
            Alert.alert('Error', 'User profile or role not loaded');
            return;
        }

        setIsLoading(true);

        try {
            // Note: Server-side trigger generates OTP, we'll use that from the response
            const visitorRecord = {
                society_id: currentRole.society_id,
                unit_id: currentRole.unit_id,
                host_id: profile.id,
                visitor_name: visitorName.trim(),
                visitor_phone: visitorPhone.trim() || null,
                vehicle_number: vehicleNumber.trim() || null,
                visitor_type: visitorType,
                expected_date: expectedDate.toISOString().split('T')[0],
                expected_time: expectedTime ? expectedTime.toTimeString().slice(0, 5) : null,
                purpose: purpose.trim() || null,
                status: 'approved' as const,
                // OTP is generated by server trigger: generate_otp_on_insert
            };

            const { data, error } = await supabase
                .from('visitors')
                .insert(visitorRecord as any)
                .select()
                .single();

            if (error) throw error;

            // Use server-generated OTP from the response
            setGeneratedOTP(data.otp);
            setVisitorData(data);

            Alert.alert(
                'Success!',
                `Visitor approved! Share the QR code or OTP: ${data.otp}`,
                [{ text: 'OK' }]
            );

        } catch (error: any) {
            console.error('Error creating visitor:', error?.message || error);
            Alert.alert('Error', error?.message || 'Failed to pre-approve visitor');
        } finally {
            setIsLoading(false);
        }
    };

    const handleReset = () => {
        setVisitorName('');
        setVisitorPhone('');
        setVehicleNumber('');
        setVisitorType('guest');
        setExpectedDate(new Date());
        setExpectedTime(null);
        setPurpose('');
        setGeneratedOTP(null);
        setVisitorData(null);
    };

    const visitorTypes: { value: VisitorType; label: string; icon: any }[] = [
        { value: 'guest', label: 'Guest', icon: 'person' },
        { value: 'delivery', label: 'Delivery', icon: 'cube' },
        { value: 'expected', label: 'Expected', icon: 'car' },
        { value: 'service', label: 'Service', icon: 'construct' },
    ];

    // Show QR Code if visitor is approved
    if (generatedOTP && visitorData) {
        return (
            <View style={styles.container}>
                <View style={styles.header}>
                    <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
                        <Ionicons name="arrow-back" size={24} color="#1e293b" />
                    </TouchableOpacity>
                    <Text style={styles.headerTitle}>Visitor Approved!</Text>
                    <View style={{ width: 24 }} />
                </View>

                <ScrollView style={styles.content} contentContainerStyle={styles.successContent}>
                    <View style={styles.successCard}>
                        <Ionicons name="checkmark-circle" size={64} color="#10b981" />
                        <Text style={styles.successTitle}>Pre-approved Successfully!</Text>
                        <Text style={styles.successSubtitle}>Share this QR code or OTP with your visitor</Text>
                    </View>

                    {/* QR Code */}
                    <View style={styles.qrContainer}>
                        <QRCode
                            value={JSON.stringify({
                                visitorId: visitorData.id,
                                otp: generatedOTP,
                                visitorName: visitorName,
                            })}
                            size={200}
                        />
                    </View>

                    {/* OTP Display */}
                    <View style={styles.otpCard}>
                        <Text style={styles.otpLabel}>Visitor OTP</Text>
                        <Text style={styles.otpValue}>{generatedOTP}</Text>
                        <Text style={styles.otpNote}>Valid for 24 hours</Text>
                    </View>

                    {/* Visitor Details */}
                    <View style={styles.detailsCard}>
                        <Text style={styles.detailLabel}>Visitor Name:</Text>
                        <Text style={styles.detailValue}>{visitorName}</Text>

                        {visitorPhone && (
                            <>
                                <Text style={styles.detailLabel}>Phone:</Text>
                                <Text style={styles.detailValue}>{visitorPhone}</Text>
                            </>
                        )}

                        <Text style={styles.detailLabel}>Expected:</Text>
                        <Text style={styles.detailValue}>
                            {expectedDate.toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' })} {expectedTime && `at ${expectedTime.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}`}
                        </Text>
                    </View>

                    <TouchableOpacity style={styles.doneButton} onPress={handleReset}>
                        <Text style={styles.doneButtonText}>Pre-approve Another Visitor</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={styles.secondaryButton} onPress={() => router.replace('/(resident)')}>
                        <Text style={styles.secondaryButtonText}>Back to Home</Text>
                    </TouchableOpacity>
                </ScrollView>
            </View>
        );
    }

    return (
        <View style={styles.container}>
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
                    <Ionicons name="arrow-back" size={24} color="#1e293b" />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Pre-approve Visitor</Text>
                <View style={{ width: 24 }} />
            </View>

            <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
                {/* Visitor Type Selection */}
                <Text style={styles.sectionTitle}>Visitor Type</Text>
                <View style={styles.typeGrid}>
                    {visitorTypes.map((type) => (
                        <TouchableOpacity
                            key={type.value}
                            style={[
                                styles.typeCard,
                                visitorType === type.value && styles.typeCardActive,
                            ]}
                            onPress={() => setVisitorType(type.value)}
                        >
                            <Ionicons
                                name={type.icon}
                                size={32}
                                color={visitorType === type.value ? '#3b82f6' : '#64748b'}
                            />
                            <Text
                                style={[
                                    styles.typeLabel,
                                    visitorType === type.value && styles.typeLabelActive,
                                ]}
                            >
                                {type.label}
                            </Text>
                        </TouchableOpacity>
                    ))}
                </View>

                {/* Visitor Details Form */}
                <Text style={styles.sectionTitle}>Visitor Details</Text>

                <Text style={styles.label}>Visitor Name *</Text>
                <TextInput
                    style={styles.input}
                    placeholder="Enter visitor name"
                    value={visitorName}
                    onChangeText={setVisitorName}
                    editable={!isLoading}
                />

                <Text style={styles.label}>Phone Number *</Text>
                <TextInput
                    style={styles.input}
                    placeholder="Enter phone number"
                    value={visitorPhone}
                    onChangeText={setVisitorPhone}
                    keyboardType="phone-pad"
                    editable={!isLoading}
                />

                <Text style={styles.label}>Vehicle Number (Optional)</Text>
                <TextInput
                    style={styles.input}
                    placeholder="e.g., MH 01 AB 1234"
                    value={vehicleNumber}
                    onChangeText={setVehicleNumber}
                    autoCapitalize="characters"
                    editable={!isLoading}
                />

                <DateInput
                    label="Expected Date"
                    value={expectedDate}
                    onChange={setExpectedDate}
                    mode="date"
                    minimumDate={new Date()}
                    required
                />

                <DateInput
                    label="Expected Time (Optional)"
                    value={expectedTime || new Date()}
                    onChange={setExpectedTime}
                    mode="time"
                    placeholder="Select time"
                />

                <Text style={styles.label}>Purpose (Optional)</Text>
                <TextInput
                    style={[styles.input, styles.textArea]}
                    placeholder="Purpose of visit"
                    value={purpose}
                    onChangeText={setPurpose}
                    multiline
                    numberOfLines={3}
                    editable={!isLoading}
                />

                {/* Submit Button */}
                <TouchableOpacity
                    style={[styles.submitButton, isLoading && styles.submitButtonDisabled]}
                    onPress={handleSubmit}
                    disabled={isLoading}
                >
                    {isLoading ? (
                        <ActivityIndicator color="#fff" />
                    ) : (
                        <>
                            <Ionicons name="qr-code" size={20} color="#fff" />
                            <Text style={styles.submitButtonText}>Generate QR & OTP</Text>
                        </>
                    )}
                </TouchableOpacity>

                <View style={styles.spacer} />
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
    },
    backButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1e293b',
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1e293b',
        marginTop: 24,
        marginBottom: 12,
    },
    typeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    typeCard: {
        width: '47%',
        padding: 16,
        borderRadius: 12,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#e2e8f0',
        alignItems: 'center',
    },
    typeCardActive: {
        borderColor: '#3b82f6',
        backgroundColor: '#eff6ff',
    },
    typeLabel: {
        fontSize: 14,
        color: '#64748b',
        marginTop: 8,
        fontWeight: '500',
    },
    typeLabelActive: {
        color: '#3b82f6',
    },
    label: {
        fontSize: 14,
        fontWeight: '500',
        color: '#1e293b',
        marginBottom: 8,
        marginTop: 16,
    },
    input: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        color: '#1e293b',
    },
    textArea: {
        minHeight: 80,
        textAlignVertical: 'top',
    },
    submitButton: {
        backgroundColor: '#3b82f6',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginTop: 24,
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    submitButtonDisabled: {
        backgroundColor: '#94a3b8',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    successContent: {
        paddingVertical: 20,
        alignItems: 'center',
    },
    successCard: {
        alignItems: 'center',
        marginBottom: 32,
    },
    successTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1e293b',
        marginTop: 16,
    },
    successSubtitle: {
        fontSize: 14,
        color: '#64748b',
        marginTop: 8,
        textAlign: 'center',
    },
    qrContainer: {
        backgroundColor: '#fff',
        padding: 24,
        borderRadius: 16,
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    otpCard: {
        backgroundColor: '#fff',
        padding: 24,
        borderRadius: 16,
        alignItems: 'center',
        marginBottom: 24,
        width: '100%',
    },
    otpLabel: {
        fontSize: 14,
        color: '#64748b',
        marginBottom: 8,
    },
    otpValue: {
        fontSize: 48,
        fontWeight: 'bold',
        color: '#3b82f6',
        letterSpacing: 8,
    },
    otpNote: {
        fontSize: 12,
        color: '#94a3b8',
        marginTop: 8,
    },
    detailsCard: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 12,
        width: '100%',
        marginBottom: 24,
    },
    detailLabel: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 8,
        textTransform: 'uppercase',
    },
    detailValue: {
        fontSize: 16,
        color: '#1e293b',
        fontWeight: '500',
        marginTop: 4,
    },
    doneButton: {
        backgroundColor: '#3b82f6',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        width: '100%',
        marginBottom: 12,
    },
    doneButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    secondaryButton: {
        backgroundColor: 'transparent',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        width: '100%',
    },
    secondaryButtonText: {
        color: '#3b82f6',
        fontSize: 16,
        fontWeight: '600',
    },
    spacer: {
        height: 40,
    },
});
